### ISSUE TITLE
Issue on page /openmp_c/1_IntroductionOfOpenMP.html

### ISSUE THREAD

**Issue by sha-linimoorthy** [passlab/OpenMPProgrammingBook#7]
# Issue Template

## Description
Grammatical Error in OpenMPProgrammingBook

## Steps to Reproduce
1. Navigate to [https://passlab.github.io/OpenMPProgrammingBook/openmp_c/1_IntroductionOfOpenMP.html]
2. Scroll down to section 1.1.3. OpenMP Fork-Join Execution Model
3. Below the figure, there is a grammatical error: the word "Drwa" makes no sense.

## Expected Behavior
The grammatical error should be corrected to align with the illustrated content or the phrase "In the above figure."

## Actual Behavior
A typographical error is present.

## Screenshots or Additional Information (if applicable)
![Screenshot](https://github.com/passlab/OpenMPProgrammingBook/assets/109151905/a9b1681f-3b4a-4ace-bd74-6a3d52659bfc)

---

**Comment by XinyaoYI** [comment]
Thank you for noticing the typo and bringing it to our attention. The mistake has been corrected.
