### ISSUE TITLE
Issue on page /openmp_c/1_IntroductionOfOpenMP.html

### ISSUE THREAD

**Issue by sha-linimoorthy** [passlab/OpenMPProgrammingBook#8]
### Description
The spelling of the word "place" appears to be incorrect on the webpage. It is currently written as "olace"

### Expected Behavior
The correct spelling should be "place"

### Actual Behavior
The current spelling on the webpage is "olace"

### Screenshots or URLs
![image](https://github.com/passlab/OpenMPProgrammingBook/assets/109151905/276088e8-62b5-4312-8093-1a34b8befd68)

**Comment by XinyaoYI** [comment]
Thank you for noticing the typo and bringing it to our attention. The mistake has been corrected.
