### ISSUE TITLE
Issue on page /openmp_c/2_Syntax.html

### ISSUE THREAD

**Issue by diegomagela** [passlab/OpenMPProgrammingBook#9]
Typo in Section **1.2.1. How to compile OpenMP programs?**

> When compiling OpenMP programs, you need to use ~~comiler~~ **compiler** flags to enable OpenMP, such as –openmp, -xopenmp, -fopenmp, -mp

**Comment by XinyaoYI** [comment]
Thank you for noticing the typo and bringing it to our attention. The mistake has been corrected.
